# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_user_id', models.CharField(max_length=225)),
                ('sessionid', models.CharField(max_length=225)),
                ('save_date', models.DateTimeField(verbose_name='save date')),
                ('expire_date', models.DateTimeField(verbose_name='expire date')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
            ],
        ),
    ]
