# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
